/* FieldInspect Pro 1.8.0 feature engine */
(function(){
'use strict';
const TKEY='fieldinspect:checklist-templates:v1';
const builtins={
 'Electrical Safety':[['Main supply','Verify incoming supply and isolation point'],['Distribution board','Check enclosure, labeling, breakers and covers'],['Earthing & bonding','Verify protective conductors and bonding continuity'],['RCD / protection','Verify RCD/RCBO operation and test records'],['Cables & containment','Inspect cable condition, routing and support'],['Socket outlets','Check condition and polarity'],['Lighting','Check normal and emergency lighting']],
 'Fire Safety':[['Fire extinguishers','Check type, condition, location and service date'],['Fire alarm','Check panel, detectors and call points'],['Emergency exits','Verify exits are clear, signed and accessible'],['Emergency lighting','Check operation and test records'],['Fire doors','Check rating, closers, seals and condition'],['Fire signage','Verify signs are visible and current']],
 'Property Handover':[['External areas','Check access, drainage, walls and finishes'],['Electrical','Check distribution, outlets, lighting and controls'],['Plumbing','Check fixtures, valves, leaks and drainage'],['Doors & windows','Check operation, locks, glazing and seals'],['Finishes','Check walls, floors and ceilings'],['Safety systems','Check alarms, extinguishers and emergency systems']],
 'Workplace Safety':[['Access & housekeeping','Check walkways, storage and housekeeping'],['Electrical safety','Check exposed hazards, panels and temporary supplies'],['PPE','Verify required PPE is available and used'],['Fire safety','Check extinguishers, exits and alarms'],['First aid','Verify first-aid equipment and signage'],['Working at height','Check ladders, platforms and edge protection']]
};
const s=()=>window.FIELDINSPECT_GET_STATE?.();
const save=()=>{window.FIELDINSPECT_PERSIST?.();window.saveCurrentToHistory?.().catch(()=>{})};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.getElementById('fi18css'))return;const x=document.createElement('style');x.id='fi18css';x.textContent='.fi18{position:fixed;inset:0;z-index:1000;background:rgba(2,6,23,.58);backdrop-filter:blur(4px);display:flex;align-items:center;justify-content:center;padding:16px}.fi18.hidden{display:none}.fi18panel{width:min(1180px,96vw);max-height:92vh;overflow:auto;background:#fff;border:1px solid #e2e8f0;border-radius:22px;box-shadow:0 30px 80px rgba(2,6,23,.3)}.fi18card{border:1px solid #e2e8f0;border-radius:16px;background:#fff}.fi18btn{border:1px solid #cbd5e1;border-radius:9px;padding:8px 11px;font-size:11px;font-weight:800;background:#fff;color:#334155}.fi18primary{background:#4f46e5;color:#fff;border-color:#4f46e5}.fi18input{width:100%;border:1px solid #cbd5e1;border-radius:9px;padding:8px 10px;font-size:11px;background:#fff;color:#0f172a}.fi18stat{padding:14px;border:1px solid #e2e8f0;border-radius:14px}.fi18grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px}.fi18photo{border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.fi18photo img{width:100%;height:125px;object-fit:cover}.fi18check{display:grid;grid-template-columns:1.2fr 1.8fr 110px 110px 35px;gap:7px;padding:9px;border-top:1px solid #eef2f7;align-items:center}body.ui-dark .fi18panel,body.ui-dark .fi18card,body.ui-dark .fi18stat{background:#0f172a;color:#e5e7eb;border-color:#334155}body.ui-dark .fi18input,body.ui-dark .fi18btn{background:#111827;color:#f8fafc;border-color:#334155}@media(max-width:760px){.fi18check{grid-template-columns:1fr 1fr}}';document.head.appendChild(x)}
function panel(id){css();let e=document.getElementById(id);if(!e){e=document.createElement('div');e.id=id;e.className='fi18 hidden';document.body.appendChild(e)}e.classList.remove('hidden');return e}
function close(id){document.getElementById(id)?.classList.add('hidden')}
function history(){return window.readHistory?.()||[]}

function renderDashboard(){
 const e=panel('fi18Dashboard'),list=history(),q=(e.querySelector('#fi18q')?.value||'').toLowerCase(),st=e.querySelector('#fi18st')?.value||'';
 const rows=list.filter(r=>{const h=[r.reportId,r.projectName,r.clientName,r.inspectorName,r.siteLocation,r.overallStatus].join(' ').toLowerCase();return(!q||h.includes(q))&&(!st||r.status===st)}).sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0));
 const c={total:list.length,draft:0,'in-progress':0,completed:0,archived:0};list.forEach(r=>c[r.status||'draft']=(c[r.status||'draft']||0)+1);
 e.innerHTML='<div class="fi18panel"><div class="p-5 border-b border-slate-200 flex items-center justify-between gap-3"><div><div class="text-xl font-black">Dashboard</div><div class="text-xs text-slate-500">Inspection workload and recent reports</div></div><div class="flex gap-2"><button class="fi18btn fi18primary" onclick="closeFiDashboard();newInspection()">+ New inspection</button><button class="fi18btn" onclick="closeFiDashboard();openHistory()">History</button><button class="fi18btn" onclick="closeFiDashboard()">Close</button></div></div><div class="p-5 space-y-5"><div class="grid grid-cols-2 md:grid-cols-5 gap-3">'+
[['Total',c.total],['Draft',c.draft],['In progress',c['in-progress']],['Completed',c.completed],['Archived',c.archived]].map(x=>'<div class="fi18stat"><div class="text-[10px] font-bold text-slate-500">'+x[0]+'</div><div class="text-2xl font-black mt-2">'+x[1]+'</div></div>').join('')+
'</div><div class="fi18card p-4 flex flex-col md:flex-row gap-2"><input id="fi18q" class="fi18input flex-1" placeholder="Search report, client, inspector or location" value="'+esc(q)+'"><select id="fi18st" class="fi18input md:w-44"><option value="">All statuses</option><option value="draft">Draft</option><option value="in-progress">In Progress</option><option value="completed">Completed</option><option value="archived">Archived</option></select></div><div class="fi18card overflow-hidden"><div class="p-4 border-b border-slate-200 font-black text-sm">'+rows.length+' inspections shown</div>'+
(rows.slice(0,40).map(r=>'<div class="p-4 border-b border-slate-100 flex flex-col lg:flex-row lg:items-center gap-3"><div class="flex-1 min-w-0"><div class="text-[10px] font-mono font-bold">'+esc(r.reportId)+' · '+esc(r.status||'draft')+'</div><div class="font-black text-sm mt-1 truncate">'+esc(r.projectName||'Untitled inspection')+'</div><div class="text-[10px] text-slate-500">'+esc(r.clientName||'No client')+' · '+esc(r.siteLocation||'No location')+'</div></div><div class="flex gap-2"><button class="fi18btn fi18primary" onclick="closeFiDashboard();openHistoryRecord(\''+r.id+'\')">Open</button><button class="fi18btn" onclick="duplicateHistoryRecord(\''+r.id+'\');renderFiDashboard()">Duplicate</button></div></div>').join('')||'<div class="p-10 text-center text-xs text-slate-500">No matching inspections.</div>')+
'</div></div></div>';
 const qel=e.querySelector('#fi18q');if(qel)qel.oninput=renderDashboard;const sel=e.querySelector('#fi18st');if(sel){sel.value=st;sel.onchange=renderDashboard}
}
window.openFiDashboard=renderDashboard;window.closeFiDashboard=()=>close('fi18Dashboard');window.renderFiDashboard=renderDashboard;

function templates(){let custom=[];try{custom=JSON.parse(localStorage.getItem(TKEY)||'[]')}catch(_){}return Object.assign({},builtins,Object.fromEntries(custom.map(x=>[x.name,x.items])))}
function engineData(){const x=s();if(!x)return null;x.featureEngine=x.featureEngine||{};x.featureEngine.checklist=Array.isArray(x.featureEngine.checklist)?x.featureEngine.checklist:[];return x.featureEngine}
function renderEngine(){
 const e=panel('fi18Engine'),d=engineData();if(!d)return;
 const ts=templates(),rows=d.checklist;
 e.innerHTML='<div class="fi18panel"><div class="p-5 border-b border-slate-200 flex items-center justify-between"><div><div class="text-xl font-black">Inspection Engine</div><div class="text-xs text-slate-500">Custom checklists, reusable templates and corrective actions</div></div><button class="fi18btn" onclick="closeFiEngine()">Close</button></div><div class="p-5"><div class="flex flex-wrap gap-2 mb-4"><select id="fi18template" class="fi18input max-w-xs"><option value="">Load checklist template…</option>'+Object.keys(ts).map(k=>'<option>'+esc(k)+'</option>').join('')+'</select><button class="fi18btn fi18primary" onclick="applyFiTemplate()">Apply</button><button class="fi18btn" onclick="addFiCheck()">+ Checklist item</button><button class="fi18btn" onclick="saveFiTemplate()">Save reusable template</button><button class="fi18btn" onclick="openFiEvidence()">Evidence manager</button></div><div class="fi18card overflow-hidden"><div class="p-4 bg-slate-50"><div class="font-black text-sm">Current checklist</div><div class="text-[10px] text-slate-500">'+rows.length+' items · '+rows.filter(x=>x.result==='pass').length+' pass · '+rows.filter(x=>x.result==='fail').length+' fail</div></div>'+
(rows.map((r,i)=>'<div class="fi18check"><input class="fi18input" value="'+esc(r.title)+'" onchange="updateFiCheck('+i+',\'title\',this.value)"><input class="fi18input" value="'+esc(r.description)+'" onchange="updateFiCheck('+i+',\'description\',this.value)"><select class="fi18input" onchange="updateFiCheck('+i+',\'result\',this.value)"><option value="pass" '+(r.result==='pass'?'selected':'')+'>Pass</option><option value="fail" '+(r.result==='fail'?'selected':'')+'>Fail</option><option value="pending" '+(r.result==='pending'?'selected':'')+'>Pending</option><option value="na" '+(r.result==='na'?'selected':'')+'>N/A</option></select><select class="fi18input" onchange="updateFiCheck('+i+',\'severity\',this.value)"><option value="none">None</option><option value="low" '+(r.severity==='low'?'selected':'')+'>Low</option><option value="medium" '+(r.severity==='medium'?'selected':'')+'>Medium</option><option value="high" '+(r.severity==='high'?'selected':'')+'>High</option><option value="critical" '+(r.severity==='critical'?'selected':'')+'>Critical</option></select><button class="fi18btn" onclick="removeFiCheck('+i+')">×</button></div>').join('')||'<div class="p-10 text-center text-xs text-slate-500">No checklist items.</div>')+'</div><div class="fi18card p-4 mt-4"><div class="font-black text-sm">Corrective action tracking</div><div class="text-[10px] text-slate-500 mt-1">Use the action controls on each finding below.</div></div></div></div>';
}
function addFiCheck(){const d=engineData();d.checklist.push({title:'New checklist item',description:'',result:'pending',severity:'none'});save();renderEngine()}
function removeFiCheck(i){const d=engineData();d.checklist.splice(i,1);save();renderEngine()}
function updateFiCheck(i,k,v){const d=engineData();d.checklist[i][k]=v;save();renderEngine()}
function applyFiTemplate(){const n=document.getElementById('fi18template')?.value;if(!n)return;const d=engineData();d.checklist=(templates()[n]||[]).map(x=>({title:x[0],description:x[1],result:'pending',severity:'none'}));save();renderEngine();window.toast?.('Checklist template applied.')}
function saveFiTemplate(){const d=engineData(),n=prompt('Template name');if(!n?.trim())return;let a=[];try{a=JSON.parse(localStorage.getItem(TKEY)||'[]')}catch(_){}a=a.filter(x=>x.name!==n.trim());a.push({name:n.trim(),items:d.checklist.map(x=>[x.title,x.description])});localStorage.setItem(TKEY,JSON.stringify(a.slice(-30)));window.toast?.('Reusable checklist saved.')}
window.openFiEngine=renderEngine;window.closeFiEngine=()=>close('fi18Engine');window.addFiCheck=addFiCheck;window.removeFiCheck=removeFiCheck;window.updateFiCheck=updateFiCheck;window.applyFiTemplate=applyFiTemplate;window.saveFiTemplate=saveFiTemplate;

function addActions(){
 const st=s();if(!st)return;document.querySelectorAll('#defects [data-card]').forEach(card=>{
  if(card.querySelector('.fi18-action'))return;const i=Number(card.dataset.card),it=st.items?.[i];if(!it)return;it.action=it.action||{status:'not-required',owner:'',dueDate:'',note:''};
  const b=document.createElement('div');b.className='fi18-action border border-slate-200 rounded-xl bg-white p-3 mt-2';b.innerHTML='<div class="text-[10px] font-black uppercase tracking-wide text-slate-500 mb-2">Corrective action</div><div class="grid sm:grid-cols-4 gap-2"><select class="field" data-a="status"><option value="not-required">No action</option><option value="open">Open</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select><input class="field" data-a="owner" placeholder="Action owner"><input class="field" data-a="dueDate" type="date"><input class="field" data-a="note" placeholder="Corrective action / follow-up"></div>';
  card.appendChild(b);['status','owner','dueDate','note'].forEach(k=>{const x=b.querySelector('[data-a="'+k+'"]');x.value=it.action[k]||'';x.oninput=()=>{it.action[k]=x.value;save();}});
 });
}
function evidence(){
 const e=panel('fi18Evidence'),st=s();if(!st)return;const photos=[];(st.items||[]).forEach((it,ii)=>(it.photos||[]).forEach((p,pi)=>photos.push({it,ii,pi,p})));
 e.innerHTML='<div class="fi18panel"><div class="p-5 border-b border-slate-200 flex items-center justify-between"><div><div class="text-xl font-black">Evidence manager</div><div class="text-xs text-slate-500">'+photos.length+' evidence photos</div></div><button class="fi18btn" onclick="closeFiEvidence()">Close</button></div><div class="p-5 fi18grid">'+(photos.map(x=>'<div class="fi18photo"><img src="'+esc(x.p.dataUrl||x.p.url||'')+'"><div class="p-2"><div class="text-[10px] font-black truncate">'+esc(x.it.title||'Finding')+'</div><input class="fi18input mt-2" value="'+esc(x.p.caption||'')+'" placeholder="Evidence caption" onchange="updateFiCaption('+x.ii+','+x.pi+',this.value)"><div class="text-[9px] text-slate-400 mt-1">'+esc(x.p.name||'Photo')+'</div></div></div>').join('')||'<div class="col-span-full p-10 text-center text-xs text-slate-500">No evidence photos yet.</div>')+'</div></div>';
}
function updateFiCaption(i,p,v){const st=s();if(st?.items?.[i]?.photos?.[p]){st.items[i].photos[p].caption=v;save()}}
window.openFiEvidence=evidence;window.closeFiEvidence=()=>close('fi18Evidence');window.updateFiCaption=updateFiCaption;

function reportAppend(){
 const st=s(),sheet=document.getElementById('reportSheet');if(!st||!sheet)return;document.getElementById('fi18ReportEngine')?.remove();
 const d=st.featureEngine||{},c=d.checklist||[],acts=(st.items||[]).filter(x=>x.action&&x.action.status&&x.action.status!=='not-required');if(!c.length&&!acts.length)return;
 const sec=document.createElement('section');sec.id='fi18ReportEngine';sec.style.cssText='margin:26px 30px 0;padding:16px;border:1px solid #e2e8f0;border-radius:10px;background:#fff;color:#0f172a;page-break-inside:avoid';
 let h='<div style="font-weight:800;font-size:15px;margin-bottom:9px">Inspection Checklist</div>';
 if(c.length)h+='<table style="width:100%;border-collapse:collapse;font-size:10px"><tr><th style="text-align:left;padding:5px;border-bottom:1px solid #cbd5e1">Item</th><th style="text-align:left;padding:5px;border-bottom:1px solid #cbd5e1">Requirement</th><th style="padding:5px;border-bottom:1px solid #cbd5e1">Result</th><th style="padding:5px;border-bottom:1px solid #cbd5e1">Severity</th></tr>'+c.map(x=>'<tr><td style="padding:5px;border-bottom:1px solid #e2e8f0">'+esc(x.title)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0">'+esc(x.description)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0;text-align:center">'+esc(x.result)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0;text-align:center">'+esc(x.severity)+'</td></tr>').join('')+'</table>';
 if(acts.length)h+='<div style="font-weight:800;font-size:13px;margin:18px 0 7px">Corrective Actions</div><table style="width:100%;border-collapse:collapse;font-size:10px"><tr><th style="text-align:left;padding:5px;border-bottom:1px solid #cbd5e1">Finding</th><th style="text-align:left;padding:5px;border-bottom:1px solid #cbd5e1">Owner</th><th style="padding:5px;border-bottom:1px solid #cbd5e1">Due</th><th style="padding:5px;border-bottom:1px solid #cbd5e1">Status</th><th style="text-align:left;padding:5px;border-bottom:1px solid #cbd5e1">Action</th></tr>'+acts.map(x=>'<tr><td style="padding:5px;border-bottom:1px solid #e2e8f0">'+esc(x.title)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0">'+esc(x.action.owner)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0;text-align:center">'+esc(x.action.dueDate)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0;text-align:center">'+esc(x.action.status)+'</td><td style="padding:5px;border-bottom:1px solid #e2e8f0">'+esc(x.action.note)+'</td></tr>').join('')+'</table>';
 sec.innerHTML=h;sheet.appendChild(sec);
}
function launchButtons(){if(document.getElementById('fi18DashboardBtn'))return;const account=document.getElementById('accountButton');if(!account)return;const mk=(id,icon,label,fn)=>{const b=document.createElement('button');b.id=id;b.className='icon-action';b.title=label;b.innerHTML='<i data-lucide="'+icon+'"></i><span class="hidden xl:inline">'+label+'</span>';b.onclick=fn;return b};account.parentElement.insertBefore(mk('fi18DashboardBtn','layout-dashboard','Dashboard',renderDashboard),account);account.parentElement.insertBefore(mk('fi18EngineBtn','list-checks','Engine',renderEngine),account);window.lucide?.createIcons?.()}
function editorLauncher(){if(document.getElementById('fi18Launch'))return;const findings=document.getElementById('defects')?.closest('.rounded-2xl');if(!findings)return;const x=document.createElement('div');x.id='fi18Launch';x.className='rounded-2xl border border-slate-200 overflow-hidden';x.innerHTML='<div class="p-4 bg-slate-50 flex items-center justify-between"><div><div class="font-black text-sm">Inspection engine</div><div class="text-[10px] text-slate-500">Checklist, corrective actions and evidence</div></div><div class="flex gap-2"><button class="fi18btn" onclick="openFiEngine()">Checklist</button><button class="fi18btn" onclick="openFiEvidence()">Evidence</button></div></div>';findings.parentElement.insertBefore(x,findings)}
function reportObserver(){const app=document.getElementById('app');if(!app)return;let observer=null;const refresh=()=>{if(observer)observer.disconnect();try{editorLauncher();addActions();reportAppend()}finally{if(observer)observer.observe(app,{subtree:true,childList:true})}};observer=new MutationObserver(refresh);refresh()}
function init(){css();launchButtons();reportObserver()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();